### ISSUE TITLE
Error "An error occurred writing to [...], does the path exist?"

### ISSUE THREAD

**Issue by juriadams** [inexio/angular-build-info#1]
**Issue from old Repository [4dams/angular-build-info](https://github.com/4dams/angular-build-info/issues/1)** by @PeziBuuu:

Hey, I just installed your plugin and run 'angular-build-info --init' and then i get following error:
An error occured writing to D:\Programme\Development\PMI\pmi-client/src/build.ts, does the path exist?

The file exist. I also tried to remove it and run the command, but still the same. Even if i create the file and run the command 'angular-build-info', I get the same error. Seems the system can'
t or won't find the file.

![71821357-36256400-3092-11ea-8199-5bc36704e8ae](https://user-images.githubusercontent.com/28960614/71821772-47bb3b80-3093-11ea-8cd7-ee657656b4fb.png)

![71821293-09714c80-3092-11ea-8667-56fdc6ec3eff](https://user-images.githubusercontent.com/28960614/71821791-5275d080-3093-11ea-8070-e345b9a019a6.png)

![71821462-813f7700-3092-11ea-8f88-196b73837702](https://user-images.githubusercontent.com/28960614/71821797-56a1ee00-3093-11ea-8eaa-8fb988c2a65b.png)

Hope you can help me.

**Comment by juriadams** [comment]
By looking at your screenshots briefly: It may be that Windows is unable to find the path because we are adding forward slashes (`/`) instead of backward slashes (`\`) to the path.

I will investigate further once I am at my Windows machine this evening.

**Comment by juriadams** [comment]
**Comment from @PeziBuuu in [the old repo](https://github.com/4dams/angular-build-info/issues/1):**

Thanks for the fast reply. I was just going to write you the same. It has to do with the windows path of the angular app. Windows add the backsplash and while you have the Forwardslash in your code and then the system can't find the file, because the path is obviously wrong. Hope this will help you.

**Comment by juriadams** [comment]
Probably the easiest way to fix this would be by using Node's [`os.platform()`](https://nodejs.org/api/os.html#os_os_platform) and check if the platform is `win32`. Then replace the slashes accordingly. Will try this approach later.

**Comment by PeziBuuu** [comment]
> Probably the easiest way to fix this would be by using Node's [`os.platform()`](https://nodejs.org/api/os.html#os_os_platform) and check if the platform is `win32`. Then replace the slashes accordingly. Will try this approach later.

any progress so far?

**Comment by juriadams** [comment]
Hey there! Sorry for the late reply, I just got to my Windows machine.

I have tried running the script inside bash on Windows, PowerShell and cmd, but am unable to reproduce your error:

![oAVvFYqX](https://user-images.githubusercontent.com/28960614/72383262-6668a480-371b-11ea-9a5a-7c641dab302c.png)

Would you mind sharing your Node and your Windows version? Thanks in advance. :)

Also, I have just updated the package to version [`1.0.7`](https://www.npmjs.com/package/angular-build-info) and added that more error details are being displayed, which should ultimately tell us why the script is failing.

**Comment by PeziBuuu** [comment]
Hello,

Thanks for the hint you gave me about node and windows version. I was some versions behind for node.js. once I updated it, everything worked fine.
Sorry for the inconveniences.

Awesome work!

**Comment by juriadams** [comment]
Don't worry, glad I could help you after all! 😀
