### ISSUE TITLE
Changing the Version Number

### ISSUE THREAD

**Issue by lenichols** [inexio/angular-build-info#2]
Right now the application shows a version number of 1.0.0 is there a way to change the version number to say - 2.0.0?

**Comment by juriadams** [comment]
Hey there, sorry for the late reply.

The tool gets the version number from the Angular apps `package.json` file which is in the root folder of the app.

Once you change the version number there and run `angular-build-info` again the version number in the generated `build.ts` file will change, too.

Hope this helps!
